---

- name: Clone the TensorFlow Models to '{{ tf_models_repo_name }}' and set branch to '{{ tf_models_repo_branch }}'
  git:
    repo: https://github.com/tensorflow/models.git
    dest: "../../{{ tf_models_repo_name }}"
    force: yes
    version: "{{ tf_models_repo_branch }}"
  register: tf_models_repo_state
