---

- name: Check if FFMPEG is installed
  stat: path=/usr/local/bin/ffmpeg
  register: ffmpeg_installed

- name: Install FFMPEG Dependencies
  apt: name={{ item }} state=latest
  with_items:
    - yasm
    - libmp3lame-dev
    - libtheora-dev
    - libvorbis-dev
  become: yes

- block:
    - name: Download and unpack FFMPEG
      unarchive: src=http://ffmpeg.org/releases/ffmpeg-3.1.3.tar.bz2 dest=/home/{{ ansible_user_id }} copy=no

    - name: Configure FFMPEG
      shell: ./configure --enable-pic --enable-shared
      args:
        chdir: "/home/{{ ansible_user_id }}/ffmpeg-3.1.3"

    - name: Build FFMPEG
      make: target=all
      args:
        chdir: "/home/{{ ansible_user_id }}/ffmpeg-3.1.3"

    - name: Install FFMPEG
      make: target=install
      args:
        chdir: "/home/{{ ansible_user_id }}/ffmpeg-3.1.3"
      become: yes
  when:
    - not ffmpeg_installed.stat.exists

- name: Add /usr/local/lib to system library paths
  lineinfile:
    dest: /etc/ld.so.conf.d/ffmpeg.conf
    create: yes
    line: /usr/local/lib
  become: yes
  register: add_usr_local_libs

- name: Reload list of system-wide library paths
  command: ldconfig
  become: yes
  when: add_usr_local_libs.changed
