---

- include: ffmpeg.yml

- name: Check if OpenCV is already installed
  stat: path=/usr/local/lib/libopencv_core.so.3.1.0
  register: opencv_installed

- name: Install OpenCV Dependencies
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - libgtk2.0-dev
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - python-dev
    - python-numpy
    - libtbb-dev
    - libjpeg-dev
    - libjasper-dev
    - libdc1394-22-dev
  become: yes

- block:
    - name: Download OpenCV
      unarchive: src=https://github.com/Itseez/opencv/archive/3.1.0.zip dest=/home/{{ ansible_user_id }} copy=no creates=/home/{{ ansible_user_id }}/opencv-3.1.0

    - name: Create Build folder for OpenCV
      file: path="/home/{{ ansible_user_id }}/opencv-3.1.0/release" state=directory 

    - name: CMake for OpenCV
      shell: |
        /bin/bash -ic "cmake
        -D CMAKE_BUILD_TYPE=RELEASE
        -D CMAKE_INSTALL_PREFIX=/usr/local
        -D WITH_TBB=ON
        -D WITH_V4L=ON
        -D WITH_QT=ON
        -D USE_GStreamer=ON
        -D WITH_OPENGL=ON
        -D WITH_CUDA=ON # TODO!
        -D CUDA_FAST_MATH=1 # TODO!
        -D WITH_CUBLAS=1
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules
        -D WITH_IPP=ON
        -D INSTALL_PYTHON_EXAMPLES=ON
        -D ENABLE_FAST_MATH=1 .."
      args:
        chdir: "/home/{{ ansible_user_id }}/opencv-3.1.0/release"

    - name: Build OpenCV
      make: target=all
      args:
        chdir: "/home/{{ ansible_user_id }}/opencv-3.1.0/release"

    - name: Install OpenCV
      make: target=install
      args:
        chdir: "/home/{{ ansible_user_id }}/opencv-3.1.0/release"
      become: yes
  when:
    - not opencv_installed.stat.exists

- name: Add /usr/local/lib to system library paths
  lineinfile:
    dest: /etc/ld.so.conf.d/opencv.conf
    create: yes
    line: /usr/local/lib
  become: yes
  register: add_usr_local_libs

- name: Reload list of system-wide library paths
  command: ldconfig
  become: yes
  when: add_usr_local_libs.changed
