---

- name: Clone the TensorFlow to '{{ tf_repo_name }}' and set branch to '{{ tf_repo_branch }}'
  git:
    repo: https://github.com/tensorflow/tensorflow.git
    dest: "../../{{ tf_repo_name }}"
    force: yes
    version: "{{ tf_repo_branch }}"
  register: tf_repo_state

- name: Setup Bazel required to build TensorFlow
  import_role:
    name: bazel
    allow_duplicates: false
