---

- name: Add user {{ ansible_user_id }} to group audio and video
  user: name={{ ansible_user_id }} groups=video,audio append=yes
  become: yes

- name: Install dependencies through apt
  apt: name={{ item }} state=latest
  with_items:
    - protobuf-compiler
  become: yes

- name: Install dependencies through {{ pip_version }}
  pip:
    name: "{{ item }}"
    state: latest
    executable: "{{ pip_version }}"
  with_items:
    - pillow
    - lxml
    - pyyaml
    - jupyter
    - matplotlib
    - numpy
    - scipy
    - pandas
    - scikit-image
    - scikit-learn
    - ipython[all]
  become: yes

- name: Install xlib required for screen capturing
  apt: name={{ item }} state=latest
  with_items:
    - "{{ python_name }}-xlib"
    - libx11-dev
  become: yes

- name: Setup OpenCV
  import_role:
    name: opencv
    allow_duplicates: false

- name: Compile the Protobuf libraries used by TensorFlow Object Detection API
  shell: protoc object_detection/protos/*.proto --python_out=.
  args:
    chdir: "../../{{ tf_models_repo_name }}/research/"

- name: Compile the grab_screen C code used to natively grab the screen via xlib
  command: gcc -shared -O3 -Wall -fPIC -Wl,-soname,prtscn -o grab_screen.so grab_screen.c -lX11
  args:
    chdir: "../stuff/"
