---

- name: Install dependencies through apt
  apt: name={{ item }} state=latest
  with_items:
    - protobuf-compiler
  become: yes

- name: Install dependencies through pip
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  with_items:
    - pillow
    - lxml
    - pyyaml
    - jupyter
    - matplotlib
    - numpy
    - scipy
    - pandas
    - scikit-image
    - scikit-learn
    - ipython[all]
  become: yes

- name: Install xlib required for screen capturing
  apt: name={{ item }} state=latest
  with_items:
    - python3-xlib
    - libx11-dev
  become: yes

- name: Setup OpenCV
  import_role:
    name: opencv
    allow_duplicates: false

- name: Compile the Protobuf libraries used by TensorFlow Object Detection API
  shell: protoc object_detection/protos/*.proto --python_out=.
  args:
    chdir: "../../{{ tf_models_repo_name }}/research/"

