---

- name: Install xlib required for screen capturing
  apt: name={{ item }} state=latest
  with_items:
    - python3-xlib
    - libx11-dev
  become: yes

#- name: Install dependencies through pip
#  pip:
#    name: {{ item }}
#    state: latest
#    executable: pip3
#  with_items:
#    - 
#    - 
#  become: yes
