---
- hosts: local

  roles:
  - { role: local_load_config, tags: ['always'] }

  - { role: provisioning_metadata_start, tags: ['always'] }

  - { role: tensorflow, tags: ['tensorflow'] }

  - { role: tensorflow_models, tags: ['tensorflow_models'] }

  - { role: tf_object_detection, tags: ['tf_object_detection,'] }

  - { role: provisioning_metadata_end, tags: ['always'] }
