---
- hosts: local

  roles:
  - { role: local_load_config, tags: ['always'] }

  - { role: provisioning_metadata_start, tags: ['always'] }

  - { role: tensorflow, tags: ['tensorflow'] }

  - { role: provisioning_metadata_end, tags: ['always'] }
